### ISSUE TITLE
Locale plugin error

### ISSUE THREAD

**Issue by ashleym1972** [nkallen/cache-money#1]
When I ran with the Locale plugin I got this error:
NoMethodError (You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.indices):
  (**DELEGATION**):2:in `__send__'
  (__DELEGATION__):2:in`indices'
  (**DELEGATION**):2:in `__send__'
  (__DELEGATION__):2:in`indices'
  vendor/gems/nkallen-cache-money-0.2.5/lib/cash/query/abstract.rb:114:in `indexed_on?'
  vendor/gems/nkallen-cache-money-0.2.5/lib/cash/query/abstract.rb:56:in`cacheable?'
  vendor/gems/nkallen-cache-money-0.2.5/lib/cash/query/abstract.rb:15:in `perform'
  vendor/gems/nkallen-cache-money-0.2.5/lib/cash/query/abstract.rb:7:in`perform'
  vendor/gems/nkallen-cache-money-0.2.5/lib/cash/finders.rb:24:in `find_every'
  vendor/gems/mislav-will_paginate-2.2.3/lib/will_paginate/finder.rb:164:in`method_missing'
  app/controllers/application_controller.rb:69:in `set_locale_from_request'

Which was caused by the Locale ActiveRecords being located in the vendor tree and not our main tree. To solve this we added this line to abstract.rb:52

```
  def cacheable?(*optionss)
```
-        return false unless @active_record.methods.include?(:indices)
      optionss.each { |options| return unless safe_options_for_cache?(options) }

**Comment by shanel** [comment]
Has there been any other fix for this?  I tried this fix out and found that it ended up meaning nothing would end up getting cached...

**Comment by ashleym1972** [comment]
Sorry, I didn't update. We found the fix didn't work out. We ended up moving the Locale classes to the model. There is really no other way of fixing this.

**Comment by shanel** [comment]
Do you mean you moved the file that defined Locale to app/models out of vendor?  Did you still have to make the change in the code?

Or do you mean you had to take the code in the Locale plugin and put it directly into any of the models that were going to use it?

**Comment by shanel** [comment]
Think I found the fix:

in abstract.rb:

```
  def indexed_on?(attributes)
    begin
      indices.detect { |index| index == attributes }
    rescue NoMethodError
      return nil 
    end 
  end
```

**Comment by ashleym1972** [comment]
That could do it. We just moved the locale.rb file to our models directory.

**Comment by xlash** [comment]
That worked for me!!! for an unknown reason, this ticket's info is not easily found via a google search of the error. It would be great to integrate it into the main rep.

**Comment by ngmoco** [comment]
Committed it to my fork.
