### ISSUE TITLE
Fails on AR:base create transactions 

### ISSUE THREAD

**Issue by parolkar** [nkallen/cache-money#7]
I am on ruby 1.8.7 , Rails 2.3.2 , cache-money 0.2.5

This works 

> Location.new(:lat => 12.1, :lng => 12.2)
# <Location id: nil, lat: #<BigDecimal:3e33e44,'0.121E2',8(8)>, lng: #<BigDecimal:3e33df4,'0.122E2',8(8)>, address: nil, city: nil, state: nil, country: nil, pincode: nil, created_at: nil, updated_at: nil>

This fails

> Location.create(:lat => 12.1, :lng => 12.2)

ArgumentError: wrong number of arguments (4 for 2)
    from /vendor/gems/nkallen-cache-money-0.2.5/lib/cash/buffered.rb:123:in `set'
    from /vendor/gems/nkallen-cache-money-0.2.5/lib/cash/buffered.rb:123:in`send'
    from /vendor/gems/nkallen-cache-money-0.2.5/lib/cash/buffered.rb:123:in `call'
    from /vendor/gems/nkallen-cache-money-0.2.5/lib/cash/buffered.rb:94:in`perform_commands'
    from /vendor/gems/nkallen-cache-money-0.2.5/lib/cash/buffered.rb:93:in `each'
    from /vendor/gems/nkallen-cache-money-0.2.5/lib/cash/buffered.rb:93:in`perform_commands'
    from /vendor/gems/nkallen-cache-money-0.2.5/lib/cash/buffered.rb:75:in `flush'
    from /vendor/gems/nkallen-cache-money-0.2.5/lib/cash/transactional.rb:19:in`transaction'
    from /vendor/gems/nkallen-cache-money-0.2.5/lib/cache_money.rb:50:in `transaction'
    from /vendor/rails/activerecord/lib/active_record/transactions.rb:228:in`with_transaction_returning_status'
    from /vendor/rails/activerecord/lib/active_record/transactions.rb:196:in `save'
    from /vendor/rails/activerecord/lib/active_record/transactions.rb:208:in`rollback_active_record_state!'
    from /vendor/rails/activerecord/lib/active_record/transactions.rb:196:in `save'
    from /vendor/rails/activerecord/lib/active_record/base.rb:728:in`create'
    from (irb):1

Help with this...

**Comment by parolkar** [comment]
This is fixed in , http://github.com/parolkar/cache-money/tree/master
